### ISSUE TITLE
[Feature]: Documention for chartUtils

### ISSUE THREAD

**Issue by Lcharvol** [tremorlabs/tremor-raw#86]
### What problem does this feature solve?

Can you rewrite this part of the documentation? https://tremor.so/docs/utilities/chartUtils

Several points are really very blurry:

- where chartUtils.ts should be placed and where should it be imported
- `make sure the path to this file is inlcuded in the tailwind.config content section` in which section of the tailwind.config this path should be included?

**Comment by severinlandolt** [comment]
Hi @Lcharvol! Thanks for your feedback. We assume that users start with the installation process first. In that section, you will set up the project structure, and all questions raised are addressed there. We include this in the installation section because it depends on the framework in use.

I also added an extra section to the utils documentation, providing a hint to the relevant installation section: https://tremor.so/docs/utilities/chartUtils#project-structure
